
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Disable security for development
      - bootstrap.memory_lock=true   # Lock memory to improve performance
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    

  redis:
    image: redis:7.0
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  es_data:
  redis_data:
  